### ISSUE TITLE
我感觉预处理完数据后，使用run.py依旧没有办法执行到主函数

### ISSUE THREAD

**Issue by huangzhaor** [zezhishao/STID#15]
from basicts import launch_training
首先，上述会报错。basicts内部似乎没有launch_training
即使改成from basicts.launcher import launch_training，也无法运行额。
更为重要的是，不知道是如何落实到训练和预测的。感觉缺失了一部分，只有数据预处理和模型骨架和参数设置的部分。可能是我没有找到，还望指点。

**Comment by zezhishao** [comment]
我没有复现出您的这个bug，有更多的信息吗？
launch_training[在这里](https://github.com/zezhishao/STID/blob/f9801a5d4939e7d3eb100525c1c027cbd34630d3/basicts/launcher.py#L5).

**Comment by huangzhaor** [comment]
嗯嗯，它是这个launcher的一个子函数，通过修改成 from basicts.launcher import launch_training，执行到launch_training内部了。但是出现了一个我不知道缘由和怎么解决的报错。报错信息如下：
Traceback (most recent call last):
  File "C:\Users\Asus\Desktop\CarbonPrice\src\models\regression\code_reproduce\STID-recurrence\STID-master\STID\basicts\launcher.py", line 20, in launch_training
    easytorch.launch_training(cfg=cfg, devices=gpus, node_rank=node_rank)
  File "C:\Users\Asus\AppData\Roaming\Python\Python310\site-packages\easytorch\launcher\launcher.py", line 59, in launch_training
    cfg = init_cfg(cfg, node_rank == 0)
  File "C:\Users\Asus\AppData\Roaming\Python\Python310\site-packages\easytorch\config\utils.py", line 210, in init_cfg
    cfg = import_config(cfg, verbose=save)
  File "C:\Users\Asus\AppData\Roaming\Python\Python310\site-packages\easytorch\config\utils.py", line 173, in import_config
    cfg = __import__(path, fromlist=[cfg_name]).CFG
ModuleNotFoundError: No module named 'C:'；
我不知道这个C：的问题在哪？ 
  需要说明的是，源代码设置的是：default="examples/STID/STID_PEMS04.py", help="training config"。其中，default的路径我没有看到examples文件夹，对STID_PEMS04放置路径的设置为放在我电脑上的绝对路径的设置了，这可能出现了 'C:'。我写的代码如下，这个会出现问题吗？
parser.add_argument("-c", "--cfg", default=r"C:\Users\Asus\Desktop\CarbonPrice\src\models\regression\code_reproduce\STID-recurrence\STID-master\STID\STID_PEMS04.py", help="training config")

**Comment by zezhishao** [comment]
使用一下相对路径哈？绝对路径应该就是会报错的。
